
name: Test Solaris

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - '*'
    paths:
      - '**.sh'
      - '.github/workflows/solaris.yml'
      - '.github/workflows/nfs.yml'
      - '.github/workflows/sshfs.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nfs:
    strategy:
      fail-fast: false
      matrix:
        release: ["11.4", "11.4-gcc"]
        arch: [""]
        runs: ["ubuntu-24.04"]


    uses: ./.github/workflows/nfs.yml
    with:
      runs: ${{ matrix.runs }}
      os: solaris
      release: ${{ matrix.release }}
      arch: ${{ matrix.arch }}



   